### ISSUE TITLE
The typescript example points JK at the .ts file when it should be using the output of tsc (the .js file)

### ISSUE THREAD

**Issue by lulusrpk** [jkcfg/kubernetes#52]

**Comment by errordeveloper** [comment]
It actually doesn't matter, `jk run` recognises `.js` as well as `.ts`.

```
$ jk run -v guestbook.ts  
wrote redis-master-deployment.yaml
$ jk run -v guestbook.js
wrote redis-master-deployment.yaml
$ 
```

**Comment by errordeveloper** [comment]
It turns out the instructions work as they are because the example doesn't have any types. I'll update the instructions now. Thanks for reporting this!
