### ISSUE TITLE
Remove *Status objects

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/kubernetes#6]
We don't need the Status objects in `api.ts` and `shape.ts` and should filter them out.

**Comment by hiddeco** [comment]
I _think_ this already happened in https://github.com/jkcfg/kubernetes/pull/4/commits/5128204bde843d27e50e2ad0dcc9c3ef1e6c18b0?

**Comment by dlespiau** [comment]
The commit you point at removes the `status` field in the Kubernetes objects but the `Status` object defintioins are still in the generated ts files:

``
$ make
$ grep class.*Status src/api.ts 
    export class CustomResourceDefinitionStatus {
    export class APIServiceStatus {
    export class APIServiceStatus {
    export class DaemonSetStatus {
    export class DeploymentStatus {
    export class ReplicaSetStatus {
    export class StatefulSetStatus {
    export class DeploymentStatus {
    export class ScaleStatus {
    export class StatefulSetStatus {
    export class DaemonSetStatus {
    export class DeploymentStatus {
    export class ReplicaSetStatus {
    export class ScaleStatus {
    export class StatefulSetStatus {
    export class TokenReviewStatus {
    export class TokenReviewStatus {
...
```
